# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notifyBuyer.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11notifyBuyer.proto\"\x85\x02\n\x12NotifyBuyerRequest\x12\x0e\n\x06itemId\x18\x01 \x01(\r\x12\r\n\x05price\x18\x02 \x01(\x01\x12\x13\n\x0bproductName\x18\x03 \x01(\t\x12.\n\x08\x63\x61tegory\x18\x04 \x01(\x0e\x32\x1c.NotifyBuyerRequest.Category\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12\x19\n\x11quantityRemaining\x18\x06 \x01(\r\x12\x15\n\rsellerAddress\x18\x07 \x01(\t\x12\x0e\n\x06rating\x18\x08 \x01(\x02\"4\n\x08\x43\x61tegory\x12\x0f\n\x0b\x45LECTRONICS\x10\x00\x12\x0b\n\x07\x46\x41SHION\x10\x01\x12\n\n\x06OTHERS\x10\x02\"e\n\x13NotifyBuyerResponse\x12+\n\x06status\x18\x01 \x01(\x0e\x32\x1b.NotifyBuyerResponse.Status\"!\n\x06Status\x12\x0b\n\x07SUCCESS\x10\x00\x12\n\n\x06\x46\x41ILED\x10\x01\x32M\n\x11\x42uyerNotification\x12\x38\n\x0bNotifyBuyer\x12\x13.NotifyBuyerRequest\x1a\x14.NotifyBuyerResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notifyBuyer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_NOTIFYBUYERREQUEST']._serialized_start=22
  _globals['_NOTIFYBUYERREQUEST']._serialized_end=283
  _globals['_NOTIFYBUYERREQUEST_CATEGORY']._serialized_start=231
  _globals['_NOTIFYBUYERREQUEST_CATEGORY']._serialized_end=283
  _globals['_NOTIFYBUYERRESPONSE']._serialized_start=285
  _globals['_NOTIFYBUYERRESPONSE']._serialized_end=386
  _globals['_NOTIFYBUYERRESPONSE_STATUS']._serialized_start=353
  _globals['_NOTIFYBUYERRESPONSE_STATUS']._serialized_end=386
  _globals['_BUYERNOTIFICATION']._serialized_start=388
  _globals['_BUYERNOTIFICATION']._serialized_end=465
# @@protoc_insertion_point(module_scope)
